// react/ceta-commerce-react/app/components/ui/Button.tsx
/**
 * Button – Universeller Button-Baustein
 *
 * DUMB COMPONENT: Bekommt alles über Props, weiß nichts über die Anwendung.
 * Kann überall verwendet werden: Warenkorb, Formulare, Navigation, etc.
 */

interface ButtonProps {
  label: string;
  variant?: "primary" | "secondary" | "outline" | "ghost";
  size?: "sm" | "md" | "lg";
  onClick?: () => void;
  disabled?: boolean;
  type?: "button" | "submit" | "reset";
}

export function Button({
  label,
  variant = "primary",
  size = "md",
  onClick,
  disabled = false,
  type = "button",
}: ButtonProps) {
  const classes = [
    "btn",
    `btn--${variant}`,
    size !== "md" ? `btn--${size}` : "",
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <button
      className={classes}
      onClick={onClick}
      disabled={disabled}
      type={type}
    >
      {label}
    </button>
  );
}

// angular/ceta-commerce-angular/src/app/components/ui/button.component.ts
/**
 * Button – Wiederverwendbarer Button
 *
 * DUMB COMPONENT: Aussehen wird über input()-Signals gesteuert.
 * Klick-Events werden über output() nach oben weitergegeben.
 *
 * Angular-Konzepte: input(), output(), @if
 */

import { Component, input, output } from '@angular/core';

@Component({
  selector: 'app-button',
  templateUrl: './button.component.html',
  styleUrl: './button.component.css',
})
export class ButtonComponent {
  label = input.required<string>();
  variant = input<'primary' | 'secondary' | 'outline' | 'ghost'>('primary');
  size = input<'sm' | 'md' | 'lg'>('md');
  disabled = input(false);
  type = input<'button' | 'submit'>('button');
  clicked = output<void>();

  protected buttonClasses(): string {
    const classes = ['btn', `btn--${this.variant()}`];
    if (this.size() !== 'md') classes.push(`btn--${this.size()}`);
    return classes.join(' ');
  }
}
