// archive/react/ceta-commerce-react/app/components/ui/TextArea.tsx
/**
 * TextArea – Mehrzeiliges Textfeld
 *
 * DUMB COMPONENT: Ein Textarea mit Label und optionaler Fehlermeldung.
 */

interface TextAreaProps {
  label: string;
  value: string;
  onChange: (value: string) => void;
  placeholder?: string;
  rows?: number;
  error?: string;
  required?: boolean;
}

export function TextArea({
  label,
  value,
  onChange,
  placeholder,
  rows = 4,
  error,
  required = false,
}: TextAreaProps) {
  return (
    <div className="form-group">
      <label className="form-label">
        {label}
        {required && <span className="text-accent"> *</span>}
      </label>
      <textarea
        className={`form-input ${error ? "form-input--error" : ""}`}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        rows={rows}
        required={required}
      />
      {error && <span className="form-error">{error}</span>}
    </div>
  );
}

// angular/ceta-commerce-angular/src/app/components/ui/textarea.component.ts
/**
 * TextArea – Mehrzeiliges Eingabefeld mit Label und Fehlermeldung
 *
 * DUMB COMPONENT: Nutzt model() für Two-Way-Binding.
 *
 * Angular-Konzepte: model(), input(), @if
 */

import { Component, input, model } from '@angular/core';

@Component({
  selector: 'app-textarea',
  templateUrl: './textarea.component.html',
  styleUrl: './textarea.component.css',
})
export class TextAreaComponent {
  label = input.required<string>();
  value = model('');
  placeholder = input('');
  rows = input(4);
  error = input('');
  required = input(false);
}

<div class="form-group">
  <label class="form-label">
    {{ label() }}
    @if (required()) {
      <span class="text-accent">*</span>
    }
  </label>
  <textarea
    class="form-input"
    [class.form-input--error]="error()"
    [placeholder]="placeholder()"
    [rows]="rows()"
    [value]="value()"
    (input)="value.set($any($event.target).value)"
  ></textarea>
  @if (error()) {
    <span class="form-error">{{ error() }}</span>
  }
</div>
