// react/ceta-commerce-react/app/components/maintenance/StatusBadge.tsx
/**
 * StatusBadge – Farbcodierter Status für Wartungsanfragen
 *
 * DUMB COMPONENT: Zeigt den Status einer Wartungsanfrage als farbigen Badge.
 * Mapping: pending=gelb, scheduled=blau, in-progress=blau-dunkel, completed=grün
 */

import type { MaintenanceStatus } from "../../types";

interface StatusBadgeProps {
  status: MaintenanceStatus;
}

const statusLabels: Record<MaintenanceStatus, string> = {
  pending: "Ausstehend",
  scheduled: "Geplant",
  "in-progress": "In Bearbeitung",
  completed: "Abgeschlossen",
};

export function StatusBadge({ status }: StatusBadgeProps) {
  return (
    <span className={`badge status-badge--${status}`}>
      {statusLabels[status]}
    </span>
  );
}

// archive/angular/ceta-commerce-angular/src/app/components/maintenance/status-badge.component.ts
/**
 * StatusBadge – Farbcodierter Status für Wartungsanfragen
 *
 * DUMB COMPONENT: Zeigt den Status einer Wartungsanfrage als farbigen Badge.
 *
 * Angular-Konzepte: input()
 */

import { Component, input } from '@angular/core';
import type { MaintenanceStatus } from '../../types';

const statusLabels: Record<MaintenanceStatus, string> = {
  pending: 'Ausstehend',
  scheduled: 'Geplant',
  'in-progress': 'In Bearbeitung',
  completed: 'Abgeschlossen',
};

@Component({
  selector: 'app-status-badge',
  templateUrl: './status-badge.component.html',
  styleUrl: './status-badge.component.css',
})
export class StatusBadgeComponent {
  status = input.required<MaintenanceStatus>();

  protected label(): string {
    return statusLabels[this.status()];
  }
}

<span [class]="'badge status-badge--' + status()">
  {{ label() }}
</span>
