// angular/ceta-commerce-angular/src/app/components/product/product-grid.component.ts
/**
 * ProductGrid – Raster-Layout für Produktkarten
 *
 * DUMB COMPONENT: Verwendet Content Projection (ng-content).
 * Das Grid weiß nicht WAS drin ist.
 *
 * Angular-Konzepte: ng-content
 */

import { Component } from '@angular/core';

@Component({
  selector: 'app-product-grid',
  templateUrl: './product-grid.component.html',
  styleUrl: './product-grid.component.css',
})
export class ProductGridComponent {}

<div class="grid grid--3">
  <ng-content />
</div>

// archive/react/ceta-commerce-react/app/components/product/ProductGrid.tsx
/**
 * ProductGrid – Raster-Layout für Produktkarten
 *
 * DUMB COMPONENT: Verwendet Component Composition – die Kinder (children)
 * werden im Grid-Layout angeordnet. Das Grid weiß nicht WAS drin ist.
 */

interface ProductGridProps {
  children: React.ReactNode;
}

export function ProductGrid({ children }: ProductGridProps) {
  return <div className="grid grid--3">{children}</div>;
}
