// archive/angular/ceta-commerce-angular/src/app/components/product/variant-picker.component.ts
/**
 * VariantPicker – Auswahl der Produktvariante (Basic / Pro / Enterprise)
 *
 * DUMB COMPONENT: Zeigt alle Varianten eines Produkts und hebt die ausgewählte hervor.
 * Die Auswahl-Logik (welcher State) lebt in der Smart Component.
 *
 * Angular-Konzepte: input(), output(), @for, @if
 */

import { Component, input, output } from '@angular/core';
import type { ProductVariant } from '../../types';
import { PriceDisplayComponent } from './price-display.component';
import { BadgeComponent } from '../ui/badge.component';

const tierLabels: Record<string, string> = {
  basic: 'Basic',
  pro: 'Pro',
  enterprise: 'Enterprise',
};

const tierBadgeVariant: Record<string, 'neutral' | 'info' | 'accent'> = {
  basic: 'neutral',
  pro: 'info',
  enterprise: 'accent',
};

@Component({
  selector: 'app-variant-picker',
  imports: [PriceDisplayComponent, BadgeComponent],
  templateUrl: './variant-picker.component.html',
  styleUrl: './variant-picker.component.css',
})
export class VariantPickerComponent {
  variants = input.required<ProductVariant[]>();
  selectedVariantId = input.required<string>();
  select = output<string>();

  tierLabel(tier: string): string {
    return tierLabels[tier] ?? tier;
  }

  tierBadge(tier: string): 'neutral' | 'info' | 'accent' {
    return tierBadgeVariant[tier] ?? 'neutral';
  }
}

<div class="variant-picker">
  @for (variant of variants(); track variant.id) {
    <div
      class="variant-option"
      [class.variant-option--selected]="variant.id === selectedVariantId()"
      (click)="select.emit(variant.id)"
      role="button"
      tabindex="0"
      (keydown.enter)="select.emit(variant.id)"
    >
      <div>
        <div class="flex flex--gap-sm" style="align-items: center">
          <span class="variant-option__name">
            {{ tierLabel(variant.tier) }}
          </span>
          <app-badge [label]="tierLabel(variant.tier)" [variant]="tierBadge(variant.tier)" />
          @if (!variant.inStock) {
            <app-badge label="Nicht verfügbar" variant="error" />
          }
        </div>
      </div>
      <app-price-display [price]="variant.price" />
    </div>
  }
</div>

// archive/react/ceta-commerce-react/app/components/product/VariantPicker.tsx
/**
 * VariantPicker – Auswahl der Produktvariante (Basic / Pro / Enterprise)
 *
 * DUMB COMPONENT: Zeigt alle Varianten eines Produkts und hebt die ausgewählte hervor.
 * Die Auswahl-Logik (welcher State) lebt in der Smart Component.
 *
 * Demonstriert:
 * - Props für Daten UND Events (onSelect = Callback nach oben)
 * - Bedingtes Styling (selected)
 */

import type { ProductVariant } from "../../types";
import { PriceDisplay } from "./PriceDisplay";
import { Badge } from "../ui/Badge";

interface VariantPickerProps {
  variants: ProductVariant[];
  selectedVariantId: string;
  onSelect: (variantId: string) => void;
}

const tierLabels: Record<string, string> = {
  basic: "Basic",
  pro: "Pro",
  enterprise: "Enterprise",
};

const tierBadgeVariant: Record<string, "neutral" | "info" | "accent"> = {
  basic: "neutral",
  pro: "info",
  enterprise: "accent",
};

export function VariantPicker({
  variants,
  selectedVariantId,
  onSelect,
}: VariantPickerProps) {
  return (
    <div className="variant-picker">
      {variants.map((variant) => (
        <div
          key={variant.id}
          className={`variant-option ${
            variant.id === selectedVariantId ? "variant-option--selected" : ""
          }`}
          onClick={() => onSelect(variant.id)}
          role="button"
          tabIndex={0}
          onKeyDown={(e) => e.key === "Enter" && onSelect(variant.id)}
        >
          <div>
            <div className="flex flex--gap-sm" style={{ alignItems: "center" }}>
              <span className="variant-option__name">
                {tierLabels[variant.tier]}
              </span>
              <Badge
                label={tierLabels[variant.tier]}
                variant={tierBadgeVariant[variant.tier]}
              />
              {!variant.inStock && (
                <Badge label="Nicht verfügbar" variant="error" />
              )}
            </div>
          </div>
          <PriceDisplay price={variant.price} />
        </div>
      ))}
    </div>
  );
}
