// angular/ceta-commerce-angular/src/app/components/maintenance/request-card.component.ts
/**
 * RequestCard – Karte für eine einzelne Wartungsanfrage
 *
 * DUMB COMPONENT: Zeigt die wichtigsten Infos einer Wartungsanfrage.
 *
 * Angular-Konzepte: input(), computed()
 */

import { Component, computed, input } from '@angular/core';
import type { MaintenanceRequest } from '../../types';
import { StatusBadgeComponent } from './status-badge.component';
import { BadgeComponent } from '../ui/badge.component';

const priorityVariant: Record<string, 'neutral' | 'warning' | 'error'> = {
  low: 'neutral',
  medium: 'warning',
  high: 'error',
};

const priorityLabels: Record<string, string> = {
  low: 'Niedrig',
  medium: 'Mittel',
  high: 'Hoch',
};

@Component({
  selector: 'app-request-card',
  imports: [StatusBadgeComponent, BadgeComponent],
  templateUrl: './request-card.component.html',
  styleUrl: './request-card.component.css',
})
export class RequestCardComponent {
  request = input.required<MaintenanceRequest>();

  protected capitalizedTier = computed(() => {
    const tier = this.request().variantTier;
    return tier.charAt(0).toUpperCase() + tier.slice(1);
  });

  protected truncatedDescription = computed(() => {
    const desc = this.request().description;
    return desc.length > 120 ? desc.slice(0, 120) + '…' : desc;
  });

  protected priorityLabel = computed(
    () => priorityLabels[this.request().priority] ?? this.request().priority,
  );

  protected priorityBadgeVariant = computed(
    () => priorityVariant[this.request().priority] ?? 'neutral',
  );
}

<div class="request-card">
  <div>
    <div class="request-card__title">
      {{ request().productName }} –
      {{ capitalizedTier() }}
    </div>
    <p class="request-card__meta">{{ truncatedDescription() }}</p>
    <div class="flex flex--gap-sm mt-sm">
      <app-status-badge [status]="request().status" />
      <app-badge [label]="'Priorität: ' + priorityLabel()" [variant]="priorityBadgeVariant()" />
    </div>
  </div>
  <div class="text-sm text-muted" style="white-space: nowrap">
    {{ request().requestDate }}
  </div>
</div>

// archive/react/ceta-commerce-react/app/components/maintenance/RequestCard.tsx
/**
 * RequestCard – Karte für eine einzelne Wartungsanfrage
 *
 * DUMB COMPONENT: Zeigt die wichtigsten Infos einer Wartungsanfrage.
 */

import type { MaintenanceRequest } from "../../types";
import { StatusBadge } from "./StatusBadge";
import { Badge } from "../ui/Badge";

interface RequestCardProps {
  request: MaintenanceRequest;
}

const priorityVariant: Record<string, "neutral" | "warning" | "error"> = {
  low: "neutral",
  medium: "warning",
  high: "error",
};

const priorityLabels: Record<string, string> = {
  low: "Niedrig",
  medium: "Mittel",
  high: "Hoch",
};

export function RequestCard({ request }: RequestCardProps) {
  return (
    <div className="request-card">
      <div>
        <div className="request-card__title">
          {request.productName} – {request.variantTier.charAt(0).toUpperCase() + request.variantTier.slice(1)}
        </div>
        <p className="request-card__meta">
          {request.description.length > 120
            ? request.description.slice(0, 120) + "…"
            : request.description}
        </p>
        <div className="flex flex--gap-sm mt-sm">
          <StatusBadge status={request.status} />
          <Badge
            label={`Priorität: ${priorityLabels[request.priority]}`}
            variant={priorityVariant[request.priority]}
          />
        </div>
      </div>
      <div className="text-sm text-muted" style={{ whiteSpace: "nowrap" }}>
        {request.requestDate}
      </div>
    </div>
  );
}
