// archive/angular/ceta-commerce-angular/src/app/components/cart/cart-item-row.component.ts
/**
 * CartItemRow – Einzelne Zeile im Warenkorb
 *
 * DUMB COMPONENT: Zeigt ein Produkt im Warenkorb mit Mengensteuerung.
 * Die Änderungs-Events werden über output() nach oben weitergegeben.
 *
 * Angular-Konzepte: input(), output()
 */

import { Component, input, output } from '@angular/core';
import { PriceDisplayComponent } from '../product/price-display.component';

@Component({
  selector: 'app-cart-item-row',
  imports: [PriceDisplayComponent],
  templateUrl: './cart-item-row.component.html',
  styleUrl: './cart-item-row.component.css',
})
export class CartItemRowComponent {
  productName = input.required<string>();
  variantName = input.required<string>();
  price = input.required<number>();
  quantity = input.required<number>();
  increase = output<void>();
  decrease = output<void>();
  remove = output<void>();
}

<div class="cart-item">
  <div class="cart-item__info">
    <div class="cart-item__name">{{ productName() }}</div>
    <div class="cart-item__variant">{{ variantName() }}</div>
  </div>
  <div class="cart-item__quantity">
    <button class="cart-item__quantity-btn" (click)="decrease.emit()">−</button>
    <span>{{ quantity() }}</span>
    <button class="cart-item__quantity-btn" (click)="increase.emit()">+</button>
  </div>
  <div class="cart-item__price">
    <app-price-display [price]="price() * quantity()" />
  </div>
  <button class="btn btn--ghost btn--sm" (click)="remove.emit()">✕</button>
</div>

// react/ceta-commerce-react/app/components/cart/CartItemRow.tsx
/**
 * CartItemRow – Einzelne Zeile im Warenkorb
 *
 * DUMB COMPONENT: Zeigt ein Produkt im Warenkorb mit Mengensteuerung.
 * Die Änderungs-Events werden nach oben weitergegeben.
 */

import { PriceDisplay } from "../product/PriceDisplay";

interface CartItemRowProps {
  productName: string;
  variantName: string;
  price: number;
  quantity: number;
  onIncrease: () => void;
  onDecrease: () => void;
  onRemove: () => void;
}

export function CartItemRow({
  productName,
  variantName,
  price,
  quantity,
  onIncrease,
  onDecrease,
  onRemove,
}: CartItemRowProps) {
  return (
    <div className="cart-item">
      <div className="cart-item__info">
        <div className="cart-item__name">{productName}</div>
        <div className="cart-item__variant">{variantName}</div>
      </div>
      <div className="cart-item__quantity">
        <button className="cart-item__quantity-btn" onClick={onDecrease}>
          −
        </button>
        <span>{quantity}</span>
        <button className="cart-item__quantity-btn" onClick={onIncrease}>
          +
        </button>
      </div>
      <div className="cart-item__price">
        <PriceDisplay price={price * quantity} />
      </div>
      <button className="btn btn--ghost btn--sm" onClick={onRemove}>
        ✕
      </button>
    </div>
  );
}
