// archive/angular/ceta-commerce-angular/src/app/components/layout/footer.component.ts
/**
 * Footer – Fußzeile der Anwendung
 *
 * DUMB COMPONENT: Statischer Inhalt, keine Inputs nötig.
 */

import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.css',
})
export class FooterComponent {
  readonly currentYear = new Date().getFullYear();
}

<footer class="footer">
  <div class="footer__inner">
    <div>
      <div class="footer__brand">Ceta<span>.</span></div>
      <p class="footer__text mt-sm">Spezialisierte Ausrüstung für die Baubranche</p>
    </div>
    <p class="footer__text">© {{ currentYear }} Ceta GmbH – Alle Rechte vorbehalten</p>
  </div>
</footer>

// archive/react/ceta-commerce-react/app/components/layout/Footer.tsx
/**
 * Footer – Fußzeile der Anwendung
 *
 * DUMB COMPONENT: Statischer Inhalt, keine Props nötig.
 */

export function Footer() {
  return (
    <footer className="footer">
      <div className="footer__inner">
        <div>
          <div className="footer__brand">
            Ceta<span>.</span>
          </div>
          <p className="footer__text mt-sm">
            Spezialisierte Ausrüstung für die Baubranche
          </p>
        </div>
        <p className="footer__text">
          © {new Date().getFullYear()} Ceta GmbH – Alle Rechte vorbehalten
        </p>
      </div>
    </footer>
  );
}
