// archive/angular/ceta-commerce-angular/src/app/components/layout/header.component.ts
/**
 * Header – Kopfzeile der Anwendung
 *
 * Enthält Logo, Navigation und Warenkorb-Badge.
 * Der Header braucht die Warenkorb-Anzahl als input(),
 * da der CartBadge ein Dumb Component ist.
 *
 * Angular-Konzepte: input(), Component Composition
 */

import { Component, input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NavigationComponent } from './navigation.component';
import { CartBadgeComponent } from '../cart/cart-badge.component';

@Component({
  selector: 'app-header',
  imports: [RouterLink, NavigationComponent, CartBadgeComponent],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css',
})
export class HeaderComponent {
  cartItemCount = input(0);
}

// archive/react/ceta-commerce-react/app/components/layout/Header.tsx
/**
 * Header – Kopfzeile der Anwendung
 *
 * Enthält Logo, Navigation und Warenkorb-Badge.
 * Der Header ist eine Komposition aus kleineren Komponenten.
 *
 * Hinweis: Der Header braucht die Warenkorb-Anzahl als Prop,
 * da der CartBadge ein Dumb Component ist.
 */

import { Link } from "react-router";
import { Navigation } from "./Navigation";
import { CartBadge } from "../cart/CartBadge";

interface HeaderProps {
  cartItemCount: number;
}

export function Header({ cartItemCount }: HeaderProps) {
  return (
    <header className="header">
      <div className="header__inner">
        <Link to="/" className="header__logo">
          Ceta<span>.</span>
        </Link>
        <Navigation />
        <CartBadge itemCount={cartItemCount} />
      </div>
    </header>
  );
}
