// archive/react/ceta-commerce-react/app/components/layout/PageHeader.tsx
/**
 * PageHeader – Seitenüberschrift mit optionaler Beschreibung
 *
 * DUMB COMPONENT: Wird auf jeder Unterseite als einheitlicher Kopfbereich verwendet.
 */

interface PageHeaderProps {
  title: string;
  description?: string;
}

export function PageHeader({ title, description }: PageHeaderProps) {
  return (
    <div className="page-header">
      <div className="container">
        <h1 className="page-header__title">{title}</h1>
        {description && (
          <p className="page-header__description">{description}</p>
        )}
      </div>
    </div>
  );
}

// angular/ceta-commerce-angular/src/app/components/layout/page-header.component.ts
/**
 * PageHeader – Seitenüberschrift mit optionaler Beschreibung
 *
 * DUMB COMPONENT: Wird auf jeder Unterseite als einheitlicher Kopfbereich verwendet.
 *
 * Angular-Konzepte: input(), @if
 */

import { Component, input } from '@angular/core';

@Component({
  selector: 'app-page-header',
  templateUrl: './page-header.component.html',
  styleUrl: './page-header.component.css',
})
export class PageHeaderComponent {
  title = input.required<string>();
  description = input('');
}
