// angular/ceta-commerce-angular/src/app/components/maintenance/request-list.component.ts
/**
 * RequestList – Liste von Wartungsanfragen
 *
 * DUMB COMPONENT: Rendert eine Liste von RequestCards.
 * Zeigt einen Empty State wenn keine Anfragen vorhanden sind.
 *
 * Angular-Konzepte: input(), @if, @for
 */

import { Component, input } from '@angular/core';
import type { MaintenanceRequest } from '../../types';
import { RequestCardComponent } from './request-card.component';

@Component({
  selector: 'app-request-list',
  imports: [RequestCardComponent],
  templateUrl: './request-list.component.html',
  styleUrl: './request-list.component.css',
})
export class RequestListComponent {
  requests = input.required<MaintenanceRequest[]>();
}

// react/ceta-commerce-react/app/components/maintenance/RequestList.tsx
/**
 * RequestList – Liste von Wartungsanfragen
 *
 * DUMB COMPONENT: Rendert eine Liste von RequestCards.
 * Zeigt einen Empty State wenn keine Anfragen vorhanden sind.
 */

import type { MaintenanceRequest } from "../../types";
import { RequestCard } from "./RequestCard";

interface RequestListProps {
  requests: MaintenanceRequest[];
}

export function RequestList({ requests }: RequestListProps) {
  if (requests.length === 0) {
    return (
      <div className="empty-state">
        <div className="empty-state__icon">📋</div>
        <h3 className="empty-state__title">Keine Anfragen gefunden</h3>
        <p className="empty-state__description">
          Es gibt derzeit keine Wartungsanfragen mit diesem Filter.
        </p>
      </div>
    );
  }

  return (
    <div className="flex flex--column flex--gap-md">
      {requests.map((request) => (
        <RequestCard key={request.id} request={request} />
      ))}
    </div>
  );
}
