// react/ceta-commerce-react/app/components/product/ProductCard.tsx
/**
 * ProductCard – Produktkarte für Übersichtsseiten
 *
 * DUMB COMPONENT: Zeigt ein Produkt als Karte an.
 * Bekommt alle Daten über Props – weiß nichts über Services oder Routing.
 *
 * Demonstriert:
 * - Component Composition (Card + CardBody + CardFooter)
 * - Props-Interface als Vertrag
 * - Bedingtes Rendering (variant prop)
 */

import type { Product } from "../../types";
import { Card, CardBody, CardFooter } from "../ui/Card";
import { Badge } from "../ui/Badge";
import { Button } from "../ui/Button";
import { PriceDisplay } from "./PriceDisplay";
import { getStartingPrice } from "../../services/product.service";

interface ProductCardProps {
  product: Product;
  variant?: "featured" | "compact";
  onViewDetails: (productId: string) => void;
}

export function ProductCard({
  product,
  variant = "compact",
  onViewDetails,
}: ProductCardProps) {
  const startingPrice = getStartingPrice(product);

  return (
    <Card>
      {variant === "featured" && (
        <div
          className="card__image"
          style={{ backgroundColor: "var(--color-gray-100)", display: "flex", alignItems: "center", justifyContent: "center" }}
        >
          <span style={{ fontSize: "3rem" }}>
            {product.category === "Sicherheit" && "🪖"}
            {product.category === "Vermessung" && "📐"}
            {product.category === "Sicherheitstechnik" && "🛡️"}
          </span>
        </div>
      )}
      <CardBody>
        <Badge label={product.category} variant="accent" />
        <h3 className="product-card__name">{product.name}</h3>
        <p className="product-card__description">{product.shortDescription}</p>
        <PriceDisplay price={startingPrice} showFromPrefix />
      </CardBody>
      <CardFooter>
        <Button
          label="Details ansehen"
          variant="outline"
          onClick={() => onViewDetails(product.id)}
        />
      </CardFooter>
    </Card>
  );
}

// angular/ceta-commerce-angular/src/app/components/product/product-card.component.ts
/**
 * ProductCard – Produktkarte für Übersichtsseiten
 *
 * DUMB COMPONENT: Zeigt ein Produkt als Karte an.
 * Bekommt alle Daten über input() – weiß nichts über Services oder Routing.
 *
 * Angular-Konzepte: input(), output(), inject(), @if, Component Composition
 */

import { Component, inject, input, output } from '@angular/core';
import type { Product } from '../../types';
import { ProductService } from '../../services/product.service';
import { CardComponent, CardBodyComponent, CardFooterComponent } from '../ui/card.component';
import { BadgeComponent } from '../ui/badge.component';
import { ButtonComponent } from '../ui/button.component';
import { PriceDisplayComponent } from './price-display.component';

@Component({
  selector: 'app-product-card',
  imports: [
    CardComponent,
    CardBodyComponent,
    CardFooterComponent,
    BadgeComponent,
    ButtonComponent,
    PriceDisplayComponent,
  ],
  templateUrl: './product-card.component.html',
  styleUrl: './product-card.component.css',
})
export class ProductCardComponent {
  private productService = inject(ProductService);

  product = input.required<Product>();
  variant = input<'featured' | 'compact'>('compact');
  viewDetails = output<string>();

  protected startingPrice(): number {
    return this.productService.getStartingPrice(this.product());
  }

  protected categoryEmoji(): string {
    const cat = this.product().category;
    if (cat === 'Sicherheit') return '🪖';
    if (cat === 'Vermessung') return '📐';
    if (cat === 'Sicherheitstechnik') return '🛡️';
    return '📦';
  }
}
