// archive/angular/ceta-commerce-angular/src/app/components/product/feature-list.component.ts
/**
 * FeatureList – Liste von Produkt-Features
 *
 * DUMB COMPONENT: Zeigt eine Liste von Features mit Häkchen-Icons an.
 *
 * Angular-Konzepte: input(), @for
 */

import { Component, input } from '@angular/core';

@Component({
  selector: 'app-feature-list',
  templateUrl: './feature-list.component.html',
  styleUrl: './feature-list.component.css',
})
export class FeatureListComponent {
  features = input.required<string[]>();
}

<ul class="feature-list">
  @for (feature of features(); track feature) {
    <li class="feature-list__item">
      <span class="feature-list__icon">✓</span>
      {{ feature }}
    </li>
  }
</ul>

// react/ceta-commerce-react/app/components/product/FeatureList.tsx
/**
 * FeatureList – Liste von Produkt-Features
 *
 * DUMB COMPONENT: Zeigt eine Liste von Features mit Häkchen-Icons an.
 */

interface FeatureListProps {
  features: string[];
}

export function FeatureList({ features }: FeatureListProps) {
  return (
    <ul className="feature-list">
      {features.map((feature) => (
        <li key={feature} className="feature-list__item">
          <span className="feature-list__icon">✓</span>
          {feature}
        </li>
      ))}
    </ul>
  );
}
