// react/ceta-commerce-react/app/components/product/PriceDisplay.tsx
/**
 * PriceDisplay – Preisanzeige mit Formatierung
 *
 * DUMB COMPONENT: Formatiert einen Zahlenwert als Euro-Preis.
 * Kann optional einen "ab"-Prefix anzeigen (für Übersichtsseiten).
 */

interface PriceDisplayProps {
  price: number;
  showFromPrefix?: boolean;
  size?: "sm" | "md" | "lg";
}

export function PriceDisplay({
  price,
  showFromPrefix = false,
  size = "md",
}: PriceDisplayProps) {
  const formatted = new Intl.NumberFormat("de-DE", {
    style: "currency",
    currency: "EUR",
  }).format(price);

  const sizeClass =
    size === "lg" ? "heading-3" : size === "sm" ? "text-sm" : "";

  return (
    <span className={`product-card__price ${sizeClass}`}>
      {showFromPrefix && <span>ab </span>}
      {formatted}
    </span>
  );
}

// archive/angular/ceta-commerce-angular/src/app/components/product/price-display.component.ts
/**
 * PriceDisplay – Preisanzeige mit Formatierung
 *
 * DUMB COMPONENT: Formatiert einen Zahlenwert als Euro-Preis.
 *
 * Angular-Konzepte: input(), computed()
 */

import { Component, computed, input } from '@angular/core';

@Component({
  selector: 'app-price-display',
  templateUrl: './price-display.component.html',
  styleUrl: './price-display.component.css',
})
export class PriceDisplayComponent {
  price = input.required<number>();
  showFromPrefix = input(false);
  size = input<'sm' | 'md' | 'lg'>('md');

  protected formatted = computed(() =>
    new Intl.NumberFormat('de-DE', {
      style: 'currency',
      currency: 'EUR',
    }).format(this.price()),
  );

  protected sizeClass = computed(() => {
    const s = this.size();
    return s === 'lg' ? 'heading-3' : s === 'sm' ? 'text-sm' : '';
  });
}

<span [class]="'product-card__price ' + sizeClass()">
  @if (showFromPrefix()) {
    <span>ab </span>
  }
  {{ formatted() }}
</span>
