// archive/angular/ceta-commerce-angular/src/app/components/layout/navigation.component.ts
/**
 * Navigation – Hauptnavigation der Anwendung
 *
 * DUMB COMPONENT: Rendert Navigationslinks.
 * Nutzt routerLinkActive für aktive Zustände.
 *
 * Angular-Konzepte: @for, RouterLink, RouterLinkActive
 */

import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

interface NavigationItem {
  to: string;
  label: string;
  exact: boolean;
}

const navigationItems: NavigationItem[] = [
  { to: '/', label: 'Start', exact: true },
  { to: '/products', label: 'Produkte', exact: false },
  { to: '/maintenance', label: 'Wartung', exact: false },
  { to: '/about', label: 'Über Ceta', exact: false },
];

@Component({
  selector: 'app-navigation',
  imports: [RouterLink, RouterLinkActive],
  templateUrl: './navigation.component.html',
  styleUrl: './navigation.component.css',
})
export class NavigationComponent {
  readonly items = navigationItems;
}

// react/ceta-commerce-react/app/components/layout/Navigation.tsx
/**
 * Navigation – Hauptnavigation der Anwendung
 *
 * DUMB COMPONENT: Rendert Navigationslinks.
 * Nutzt NavLink von React Router für aktive Zustände.
 */

import { NavLink } from "react-router";

interface NavigationItem {
  to: string;
  label: string;
}

const navigationItems: NavigationItem[] = [
  { to: "/", label: "Start" },
  { to: "/products", label: "Produkte" },
  { to: "/maintenance", label: "Wartung" },
  { to: "/about", label: "Über Ceta" },
];

export function Navigation() {
  return (
    <nav className="nav">
      {navigationItems.map((item) => (
        <NavLink
          key={item.to}
          to={item.to}
          className={({ isActive }) =>
            `nav__link ${isActive ? "nav__link--active" : ""}`
          }
          end={item.to === "/"}
        >
          {item.label}
        </NavLink>
      ))}
    </nav>
  );
}
