// archive/angular/ceta-commerce-angular/src/app/components/ui/badge.component.ts
/**
 * Badge – Farbiger Status-/Kategorie-Badge
 *
 * DUMB COMPONENT: Zeigt ein Label in einer farbigen Kapsel an.
 *
 * Angular-Konzepte: input()
 */

import { Component, input } from '@angular/core';

@Component({
  selector: 'app-badge',
  templateUrl: './badge.component.html',
  styleUrl: './badge.component.css',
})
export class BadgeComponent {
  label = input.required<string>();
  variant = input<'primary' | 'accent' | 'success' | 'warning' | 'error' | 'info' | 'neutral'>(
    'primary',
  );
}

// react/ceta-commerce-react/app/components/ui/Badge.tsx
/**
 * Badge – Kleine Kennzeichnung / Label
 *
 * DUMB COMPONENT: Zeigt einen farbigen Tag an.
 * Wird z.B. für Produktkategorien, Status-Anzeigen und Tier-Labels verwendet.
 */

interface BadgeProps {
  label: string;
  variant?:
    | "primary"
    | "accent"
    | "success"
    | "warning"
    | "error"
    | "info"
    | "neutral";
}

export function Badge({ label, variant = "neutral" }: BadgeProps) {
  return <span className={`badge badge--${variant}`}>{label}</span>;
}
