// archive/angular/ceta-commerce-angular/src/app/components/ui/input.component.ts
/**
 * Input – Formularfeld mit Label und Fehlermeldung
 *
 * DUMB COMPONENT: Nutzt model() für Two-Way-Binding des Werts.
 *
 * Angular-Konzepte: model(), input(), @if
 */

import { Component, input, model } from '@angular/core';

@Component({
  selector: 'app-input',
  templateUrl: './input.component.html',
  styleUrl: './input.component.css',
})
export class InputComponent {
  label = input.required<string>();
  value = model('');
  placeholder = input('');
  type = input('text');
  error = input('');
  required = input(false);
}

<div class="form-group">
  <label class="form-label">
    {{ label() }}
    @if (required()) {
      <span class="text-accent">*</span>
    }
  </label>
  <input
    class="form-input"
    [class.form-input--error]="error()"
    [type]="type()"
    [placeholder]="placeholder()"
    [value]="value()"
    (input)="value.set($any($event.target).value)"
  />
  @if (error()) {
    <span class="form-error">{{ error() }}</span>
  }
</div>

// react/ceta-commerce-react/app/components/ui/Input.tsx
/**
 * Input – Textfeld-Baustein
 *
 * DUMB COMPONENT: Ein Eingabefeld mit Label und optionaler Fehlermeldung.
 */

interface InputProps {
  label: string;
  value: string;
  onChange: (value: string) => void;
  placeholder?: string;
  type?: "text" | "email" | "number" | "search";
  error?: string;
  required?: boolean;
}

export function Input({
  label,
  value,
  onChange,
  placeholder,
  type = "text",
  error,
  required = false,
}: InputProps) {
  return (
    <div className="form-group">
      <label className="form-label">
        {label}
        {required && <span className="text-accent"> *</span>}
      </label>
      <input
        className={`form-input ${error ? "form-input--error" : ""}`}
        type={type}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        placeholder={placeholder}
        required={required}
      />
      {error && <span className="form-error">{error}</span>}
    </div>
  );
}
