// angular/ceta-commerce-angular/src/app/components/ui/select.component.ts
/**
 * Select – Dropdown-Auswahlfeld mit Label und Fehlermeldung
 *
 * DUMB COMPONENT: Nutzt model() für Two-Way-Binding.
 *
 * Angular-Konzepte: model(), input(), @if, @for
 */

import { Component, input, model } from '@angular/core';

@Component({
  selector: 'app-select',
  templateUrl: './select.component.html',
  styleUrl: './select.component.css',
})
export class SelectComponent {
  label = input.required<string>();
  value = model('');
  options = input.required<{ value: string; label: string }[]>();
  placeholder = input('');
  error = input('');
  required = input(false);
}

<div class="form-group">
  <label class="form-label">
    {{ label() }}
    @if (required()) {
      <span class="text-accent">*</span>
    }
  </label>
  <select
    class="form-input"
    [class.form-input--error]="error()"
    [value]="value()"
    (change)="value.set($any($event.target).value)"
  >
    @if (placeholder()) {
      <option value="" disabled>{{ placeholder() }}</option>
    }
    @for (option of options(); track option.value) {
      <option [value]="option.value">{{ option.label }}</option>
    }
  </select>
  @if (error()) {
    <span class="form-error">{{ error() }}</span>
  }
</div>

// react/ceta-commerce-react/app/components/ui/Select.tsx
/**
 * Select – Dropdown-Baustein
 *
 * DUMB COMPONENT: Ein Auswahlfeld mit Label und optionaler Fehlermeldung.
 */

interface SelectOption {
  value: string;
  label: string;
}

interface SelectProps {
  label: string;
  value: string;
  onChange: (value: string) => void;
  options: SelectOption[];
  placeholder?: string;
  error?: string;
  required?: boolean;
}

export function Select({
  label,
  value,
  onChange,
  options,
  placeholder,
  error,
  required = false,
}: SelectProps) {
  return (
    <div className="form-group">
      <label className="form-label">
        {label}
        {required && <span className="text-accent"> *</span>}
      </label>
      <select
        className={`form-input ${error ? "form-input--error" : ""}`}
        value={value}
        onChange={(e) => onChange(e.target.value)}
        required={required}
      >
        {placeholder && (
          <option value="" disabled>
            {placeholder}
          </option>
        )}
        {options.map((option) => (
          <option key={option.value} value={option.value}>
            {option.label}
          </option>
        ))}
      </select>
      {error && <span className="form-error">{error}</span>}
    </div>
  );
}
