// archive/angular/ceta-commerce-angular/src/app/components/cart/cart-badge.component.ts
/**
 * CartBadge – Warenkorb-Icon mit Anzahl
 *
 * DUMB COMPONENT: Zeigt die Artikelanzahl an.
 *
 * Angular-Konzepte: input(), @if, RouterLink
 */

import { Component, input } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-cart-badge',
  imports: [RouterLink],
  templateUrl: './cart-badge.component.html',
  styleUrl: './cart-badge.component.css',
})
export class CartBadgeComponent {
  itemCount = input(0);
}

<a routerLink="/cart" class="cart-badge">
  🛒 Warenkorb
  @if (itemCount() > 0) {
    <span class="cart-badge__count">{{ itemCount() }}</span>
  }
</a>

// archive/react/ceta-commerce-react/app/components/cart/CartBadge.tsx
/**
 * CartBadge – Warenkorb-Icon mit Anzahl
 *
 * DUMB COMPONENT: Zeigt die Artikelanzahl an.
 * Der Count wird von der Smart Component übergeben.
 */

import { Link } from "react-router";

interface CartBadgeProps {
  itemCount: number;
}

export function CartBadge({ itemCount }: CartBadgeProps) {
  return (
    <Link to="/cart" className="cart-badge">
      🛒 Warenkorb
      {itemCount > 0 && (
        <span className="cart-badge__count">{itemCount}</span>
      )}
    </Link>
  );
}
